# Change these first
owner: gongfuture # Your GitHub organization or username, where this repository lives
repo: upptime-status # The name of this repository
user-agent: luochu-bot # The user agent to use for requests, e.g. "luochu-bot"
sites:
  - name: 洛初 的 主页
    url: https://home.luochu.cc/
    slug: home
    type: globalping 
    location: china
    assignees:
      - gongfuture
  - name: 洛初 的 档案馆
    url: https://blog.luochu.cc/
    slug: blog
    type: globalping 
    location: china
    assignees:
      - gongfuture
  - name: 洛初 睡醒了么
    url: https://sleepy.luochu.cc/
    slug: sleepy
    type: globalping 
    location: china
    assignees:
      - gongfuture
  - name: 洛初 的 图床
    url: https://picbed.luochu.cc/
    slug: picbed
    type: globalping 
    location: china
    assignees:
      - gongfuture
  - name: 洛初 的 工具箱
    url: https://tool.luochu.cc/
    slug: tool
    type: globalping 
    location: china
    assignees:
      - gongfuture
  - name: 洛初 的 Github加速
    url: https://ghproxy.luochu.cc/
    slug: ghproxy
    type: globalping 
    location: china
    assignees:
      - gongfuture
    expectedStatusCodes:
      - 403
  - name: 洛初 的 RSSHub 实例
    url: https://rsshub.luochu.cc/
    slug: rsshub
    type: globalping 
    location: china
    assignees:
      - gongfuture
  - name: 洛初 的 Linux指令查询
    url: https://linuxcmd.luochu.cc/
    slug: linuxcmd
    type: globalping 
    location: china
    assignees:
      - gongfuture
  - name: 洛初 的 监控页
    url: https://status.luochu.cc/
    slug: status
    type: globalping 
    location: china
    assignees:
      - gongfuture
  - name: 洛初 的 服务器监控
    url: $SERVERMONITOR_URL
    slug: servermonitor
    type: globalping 
    location: china
    assignees:
      - gongfuture
  - name: 洛初 的 短链接生成
    url: $URLSHORT_URL
    slug: urlshort
    type: globalping 
    location: china
    assignees:
      - gongfuture
    expectedStatusCodes:
      - 403
  - name: 洛初 的 RSS订阅
    url: $RSSMANAGE_URL
    slug: rssmanage
    type: globalping 
    location: china
    assignees:
      - gongfuture
  - name: 服务器管理后台
    url: $BACKEND_URL
    slug: backend
    type: globalping 
    location: china
    assignees:
      - gongfuture



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: dev.status.luochu.cc
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 洛初 的 监控页
  introTitle: "这是洛初用来监控自己的一系列服务的状态页"
  introMessage: |
    可能还有一些其他的奇奇怪怪的服务(? , 会放在最下方  
    使用来自 [Upptime-status](https://github.com/luochu-bot/upptime-status) 的**实时**数据  
    <br>
    Powered by [Upptime](https://upptime.js.org/) , [Github](https://github.com) Actions, Issues, and Pages
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  customHeadHtml: |
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-5DWQQ56Z');</script>
    <!-- End Google Tag Manager -->
  customBodyHtml: |
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5DWQQ56Z"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

commitMessages:
  commitAuthorName: "luochu-bot"
  commitAuthorEmail: "bot@luochu.cc"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
